pve_group: proxmox_nodes
pve_cluster_enabled: true
pve_cluster_clustername: pvec01
pve_ceph_enabled: true
pve_ceph_pools:
  # Ceph pool used for VM disks
  - name: ceph-vm
    pgs: 32
    storage: true
    application: rbd
    rule: replicated_rule
    size: 3
    min-size: 2
  # Ceph pool used for Kubernetes PVCs
  - name: ceph-kubernetes
    pgs: 32
    storage: true
    application: rbd
    rule: replicated_rule
    size: 3
    min-size: 2
# TODO: Need to figure out how to add content types for cephfs
# iso - images, import
# snippets - snippets
pve_ceph_fs:
  - name: ceph-iso
    pgs: 16
    storage: true
    rule: replicated_rule
    mountpoint: /srv/proxmox/ceph/iso
  - name: ceph-snippets
    pgs: 16
    storage: true
    rule: replicated_rule
    mountpoint: /srv/proxmox/ceph/snippets
pve_metric_servers:
  - id: influxdb1
    port: 443
    server: influxdb.{{ network_domain_suffix }}
    type: influxdb
    protocol: https
    organization: "{{ influxdb_organization }}"
    bucket: proxmox
    token: "{{ influxdb_token }}"
    timeout: 30
    max_body_size: 25000000
    verify_certificate: true